### ISSUE TITLE
".js" in generator (jspm branch)

### ISSUE THREAD

**Issue by anorudes** [angular-class/NG6-starter#19]
Master branch:
https://github.com/angular-class/NG6-starter/blob/master/generator/component/temp.component.js
jspm branch: 
https://github.com/angular-class/NG6-starter/blob/jspm/generator/component/temp.component.js

We must remove the ".js", becouse import does not see it

**Comment by danthareja** [comment]
Good call. The reason the extra ".js" extension slipped in here is SystemJS spec (the module loader that JSPM is built on top of) actually expects these extensions to exist by default.

There is a `defaultJSExtensions` setting included that JSPM [takes advantage of](https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L10) for now making the extra extension not necessary, but in the near future we might expect to see the '.js' being required.
