### ISSUE TITLE
no gulpfile.js

### ISSUE THREAD

**Issue by asadsahi** [angular-class/NG6-starter#45]
There is a gulpfile.babel.js file at the root, how to run gulp tasks from that file?

**Comment by gdi2290** [comment]
this is a feature with gulp since it uses module for file reading which allows the user to write the gulpfile in the transpiled lang. So for this repo you're able to just type `gulp`

**Comment by asadsahi** [comment]
Thanks Patrick, worked like a charm. :). Didn't know about the change in gulp. Do you know which version of gulp that was?

**Comment by gdi2290** [comment]
it's been there are a while so I'm not sure how long. They even have typescript support as `gulpfile.ts`

**Comment by danthareja** [comment]
[3.9.0](https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#390) lets you use the babel just with the filename change. The `gulp` keyword has always been around though
